require 'micro_migrations'
require 'sinatra/activerecord/rake'
#require './app'
require 'active_record'
#require './test/model_test.rb'

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = 'test/*_test.rb'
end

task default: :test
